global.LANG_NAMES = {
	ach: 'Lwo',
	ady: 'Адыгэбзэ',
	af: 'Afrikaans',
	ak: 'Tɕɥi',
	ar: 'العربية',
	az: 'Azərbaycan dili',
	bg: 'Български',
	bn: 'বাংলা',
	ca: 'Català',
	cak: 'Maya Kaqchikel',
	cs: 'Čeština',
	cy: 'Cymraeg',
	da: 'Dansk',
	de: 'Deutsch',
	dsb: 'Dolnoserbšćina',
	el: 'Ελληνικά',
	en: 'English',
	eo: 'Esperanto',
	es: 'Español',
	et: 'eesti keel',
	eu: 'Euskara',
	fa: 'فارسی',
	ff: 'Fulah',
	fi: 'Suomi',
	fr: 'Français',
	ga: 'Gaeilge',
	gl: 'Galego',
	he: 'עברית‏',
	hi: 'हिन्दी',
	hr: 'Hrvatski',
	hsb: 'Hornjoserbšćina',
	ht: 'Kreyòl',
	hu: 'Magyar',
	id: 'Bahasa Indonesia',
	is: 'Íslenska',
	it: 'Italiano',
	ja: '日本語',
	km: 'ភាសាខ្មែរ',
	kab: 'Taqbaylit',
	kn: 'ಕನ್ನಡ',
	ko: '한국어',
	la: 'Latin',
	lb: 'Lëtzebuergesch',
	lt: 'Lietuvių',
	lv: 'Latviešu',
	mai: 'मैथिली, মৈথিলী',
	mk: 'Македонски',
	ml: 'മലയാളം',
	mr: 'मराठी',
	ms: 'Bahasa Melayu',
	mt: 'Malti',
	my: 'ဗမာစကာ',
	no: 'Norsk',
	nb: 'Norsk (bokmål)',
	ne: 'नेपाली',
	nl: 'Nederlands',
	oc: 'Occitan',
	pa: 'ਪੰਜਾਬੀ',
	pl: 'Polski',
	pt: 'Português',
	ro: 'Română',
	ru: 'Русский',
	sk: 'Slovenčina',
	sl: 'Slovenščina',
	sq: 'Shqip',
	sr: 'Српски',
	su: 'Basa Sunda',
	sv: 'Svenska',
	sw: 'Kiswahili',
	ta: 'தமிழ்',
	te: 'తెలుగు',
	tg: 'забо́ни тоҷикӣ́',
	th: 'ภาษาไทย',
	tl: 'Filipino',
	tlh: 'tlhIngan-Hol',
	tr: 'Türkçe',
	uk: 'Українська',
	ur: 'اردو',
	uz: 'O\'zbek',
	vi: 'Tiếng Việt',
	yi: 'ייִדיש',
	'zh-CN': '中文（中国）',
	'zh-TW': '中文（台灣）'
};
